version: "3"

services:
    database:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-secret}
            MYSQL_DATABASE: ${MYSQL_DATABASE:-data}
            MYSQL_USER: ${MYSQL_USER:-user}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD:-password}
        ports:
            - "${MYSQL_PORT:-3306}:3306"
